{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.metadata.name }}
data: 
  {{- range $key, $val := .Values.configmap.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}