{{- if .Values.issuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.metadata.name }}
spec:
  acme:
    # Email address used for ACME registration
    email: {{ .Values.issuer.acme.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.issuer.acme.privateKeySecretRef.name }}
    # The ACME server URL
    server: {{ .Values.issuer.acme.server }}
    # Enable the HTTP-01 challenge provider
    {{- with .Values.issuer.acme.solvers }}
    solvers:
      {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}