{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.metadata.name }}
stringData:
  {{- range $key, $val := .Values.secret.stringData }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
type: Opaque
{{- end }}